version: '3'
services:

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    image: nacho270/spring-int-testing-demo:latest
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/spring-int-testing-demo
      spring.data.mongodb.host: mongo
    ports:
      - 8080:8080
    links:
      - mysql
      - mongo