spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-int-testing-demo
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: log

  kafka:
    bootstrap-servers: "localhost:29092"
    listener:
      type: SINGLE
      ack-mode: record
    consumer:
      group-id: "intTestDemo"
      auto-offset-reset: earliest
      enagle-auto-commit: false
      isolation-level: READ_COMMITTED

payments:
  topic: payment_outcome

news:
  topic: shipment_news

userapi:
  url: https://jsonplaceholder.typicode.com/
