spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-int-testing-demo
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: log

userapi:
  url: https://jsonplaceholder.typicode.com/